import 'package:tim_ui_kit_sticker_plugin/utils/tim_custom_face_data.dart';

class TUIKitStickerConstData {
  static final List<CustomEmojiFaceData> emojiList = [
    CustomEmojiFaceData(
        name: '4349',
        icon: "面罩.png",
        isEmoji: true,
        list: [
          "微笑.png",
          "傻笑.png",
          "羡慕.png",
          "露出牙齿.png",
          "愉快.png",
          "坏笑.png",
          "苦笑.png",
          "眨眼.png",
          "害羞.png",
          "强颜微笑.png",
          "吐舌头.png",
          "满意.png",
          "捂手笑.png",
          "鼓掌.png",
          "惊喜.png",
          "嘿哈.png",
          "奸笑.png",
          "比耶.png",
          "彩虹.png",
          "你真棒.png",
          "恐怖.png",
          "嚎啕大哭.png",
          "发呆.png",
          "惊讶.png",
          "啊.png",
          "冷漠.png",
          "面罩.png",
          "爆哭.png",
          "撇嘴.png",
          "尴尬.png",
          "暴躁.png",
          "想吐.png",
          "难过.png",
          "傲慢.png",
          "困.png",
          "拽.png",
          "疑问.png",
          "不悦.png",
          "委屈.png",
          "发愁.png",
          "瞌睡.png",
          "嘟嘴.png",
          "自满的.png",
          "期待.png",
          "六六六.png",
          "眩晕.png",
          "敲头.png",
          "再见.png",
          "擦汗.png",
          "挖鼻子.png",
          "右哼哼.png",
          "嘿嘿.png",
          "可怜巴巴.png",
          "脸红.png",
          "偷看.png",
          "干饭.png",
          "推墨镜.png",
          "酸.png",
          "休息一下.png",
          "热.png",
          "发.png",
          "福到.png",
          "庆祝.png",
          "星星.png",
          "太阳.png",
          "月亮.png",
          "裂开.png",
          "变形.png",
          "哭.png",
          "在吗.png",
          "烟花.png",
          "爆竹.png",
          "笔芯.png",
          "小红花.png",
          "啤酒.png",
          "蛋糕.png",
          "礼物.png",
          "红包.png",
          "鼓掌.png",
          "愤怒.png",
          "惊恐.png",
          "红脸.png",
          "白眼.png",
          "叹气.png",
          "闭嘴.png",
          "无语.png",
          "无奈.png",
          "不高兴.png",
          "嘘.png",
          "皱眉.png",
          "哭笑.png",
          "奋斗.png",
          "流汗.png",
          "感谢.png",
          "狗子.png",
          "好的.png",
          "吃瓜.png",
          "机智.png",
          "刀.png",
          "赞.png",
          "拍手.png",
          "耶.png",
          "多谢.png",
          "过来.png",
          "拳头.png",
          "祈祷.png",
          "击拳.png",
          "炸弹.png",
          "骷髅.png",
          "衰.png",
          "便便.png",
          "拥抱.png",
          "好方.png",
          "鲜花.png",
          "花谢.png",
          "爱中国.png",
          "收到.png",
          "加油.png",
          "出差奔波中.png",
          "生病难受中.png",
          "会议轰炸中.png",
          "掉入PPT中.png",
          "休假.png",
          "疯狂打码中.png",
          "羽毛球.png",
          "篮球.png",
          "第一.png",
          "第二.png",
          "第三.png",
          "干杯.png",
          "举手.png",
          "加一.png",
          "减一.png",
          "OK.png",
          "对.png",
          "不.png",
          "满分.png",
          "给力.png",
          "桃心.png",
          "心碎.png"
        ]),
    CustomEmojiFaceData(name: 'tcc1', icon: "TUIEmoji_Smile.png", isEmoji: true, list: [
      "TUIEmoji_Like.png",
      "TUIEmoji_Ok.png",
      "TUIEmoji_Smile.png",
      "TUIEmoji_Expect.png",
      "TUIEmoji_Blink.png",
      "TUIEmoji_Guffaw.png",
      "TUIEmoji_KindSmile.png",
      "TUIEmoji_Haha.png",
      "TUIEmoji_Cheerful.png",
      "TUIEmoji_Speechless.png",
      "TUIEmoji_Amazed.png",
      "TUIEmoji_Sorrow.png",
      "TUIEmoji_Complacent.png",
      "TUIEmoji_Silly.png",
      "TUIEmoji_Lustful.png",
      "TUIEmoji_Giggle.png",
      "TUIEmoji_Kiss.png",
      "TUIEmoji_Wail.png",
      "TUIEmoji_TearsLaugh.png",
      "TUIEmoji_Trapped.png",
      "TUIEmoji_Mask.png",
      "TUIEmoji_Fear.png",
      "TUIEmoji_BareTeeth.png",
      "TUIEmoji_FlareUp.png",
      "TUIEmoji_Yawn.png",
      "TUIEmoji_Tact.png",
      "TUIEmoji_Stareyes.png",
      "TUIEmoji_ShutUp.png",
      "TUIEmoji_Sigh.png",
      "TUIEmoji_Hehe.png",
      "TUIEmoji_Silent.png",
      "TUIEmoji_Surprised.png",
      "TUIEmoji_Askance.png",
      "TUIEmoji_Shit.png",
      "TUIEmoji_Monster.png",
      "TUIEmoji_Daemon.png",
      "TUIEmoji_Rage.png",
      "TUIEmoji_Fool.png",
      "TUIEmoji_Pig.png",
      "TUIEmoji_Cow.png",
      "TUIEmoji_Ai.png",
      "TUIEmoji_Skull.png",
      "TUIEmoji_Bombs.png",
      "TUIEmoji_Coffee.png",
      "TUIEmoji_Cake.png",
      "TUIEmoji_Beer.png",
      "TUIEmoji_Flower.png",
      "TUIEmoji_Watermelon.png",
      "TUIEmoji_Rich.png",
      "TUIEmoji_Heart.png",
      "TUIEmoji_Moon.png",
      "TUIEmoji_Sun.png",
      "TUIEmoji_Star.png",
      "TUIEmoji_RedPacket.png",
      "TUIEmoji_Celebrate.png",
      "TUIEmoji_Bless.png",
      "TUIEmoji_Fortune.png",
      "TUIEmoji_Convinced.png",
      "TUIEmoji_Prohibit.png",
      "TUIEmoji_666.png",
      "TUIEmoji_857.png",
      "TUIEmoji_Knife.png",
    ])
  ];

  static final emoji4349ZhMapList = {
    "微笑": "微笑",
    "傻笑": "傻笑",
    "羡慕": "羡慕",
    "露出牙齿": "露出牙齿",
    "愉快": "愉快",
    "坏笑": "坏笑",
    "苦笑": "苦笑",
    "眨眼": "眨眼",
    "害羞": "害羞",
    "强颜微笑": "强颜微笑",
    "吐舌头": "吐舌头",
    "满意": "满意",
    "捂手笑": "捂手笑",
    "鼓掌": "鼓掌",
    "惊喜": "惊喜",
    "嘿哈": "嘿哈",
    "奸笑": "奸笑",
    "比耶": "比耶",
    "彩虹": "彩虹",
    "你真棒": "你真棒",
    "恐怖": "恐怖",
    "嚎啕大哭": "嚎啕大哭",
    "发呆": "发呆",
    "惊讶": "惊讶",
    "啊": "啊",
    "冷漠": "冷漠",
    "面罩": "面罩",
    "爆哭": "爆哭",
    "撇嘴": "撇嘴",
    "尴尬": "尴尬",
    "暴躁": "暴躁",
    "想吐": "想吐",
    "难过": "难过",
    "傲慢": "傲慢",
    "困": "困",
    "拽": "拽",
    "疑问": "疑问",
    "不悦": "不悦",
    "委屈": "委屈",
    "发愁": "发愁",
    "瞌睡": "瞌睡",
    "嘟嘴": "嘟嘴",
    "自满的": "自满的",
    "期待": "期待",
    "六六六": "六六六",
    "眩晕": "眩晕",
    "敲头": "敲头",
    "再见": "再见",
    "擦汗": "擦汗",
    "挖鼻子": "挖鼻子",
    "右哼哼": "右哼哼",
    "嘿嘿": "嘿嘿",
    "可怜巴巴": "可怜巴巴",
    "脸红": "脸红",
    "偷看": "偷看",
    "干饭": "干饭",
    "推墨镜": "推墨镜",
    "酸": "酸",
    "休息一下": "休息一下",
    "热": "热",
    "发": "发",
    "福到": "福到",
    "庆祝": "庆祝",
    "星星": "星星",
    "太阳": "太阳",
    "月亮": "月亮",
    "裂开": "裂开",
    "变形": "变形",
    "哭": "哭",
    "在吗": "在吗",
    "烟花": "烟花",
    "爆竹": "爆竹",
    "笔芯": "笔芯",
    "小红花": "小红花",
    "啤酒": "啤酒",
    "蛋糕": "蛋糕",
    "礼物": "礼物",
    "红包": "红包",
    "愤怒": "愤怒",
    "惊恐": "惊恐",
    "红脸": "红脸",
    "白眼": "白眼",
    "叹气": "叹气",
    "闭嘴": "闭嘴",
    "无语": "无语",
    "无奈": "无奈",
    "不高兴": "不高兴",
    "嘘": "嘘",
    "皱眉": "皱眉",
    "哭笑": "哭笑",
    "奋斗": "奋斗",
    "流汗": "流汗",
    "感谢": "感谢",
    "狗子": "狗子",
    "好的": "好的",
    "吃瓜": "吃瓜",
    "机智": "机智",
    "刀": "刀",
    "赞": "赞",
    "拍手": "拍手",
    "耶": "耶",
    "多谢": "多谢",
    "过来": "过来",
    "拳头": "拳头",
    "祈祷": "祈祷",
    "击拳": "击拳",
    "炸弹": "炸弹",
    "骷髅": "骷髅",
    "衰": "衰",
    "便便": "便便",
    "拥抱": "拥抱",
    "好方": "好方",
    "鲜花": "鲜花",
    "花谢": "花谢",
    "爱中国": "爱中国",
    "收到": "收到",
    "加油": "加油",
    "出差奔波中": "出差奔波中",
    "生病难受中": "生病难受中",
    "会议轰炸中": "会议轰炸中",
    "掉入PPT中": "掉入PPT中",
    "休假": "休假",
    "疯狂打码中": "疯狂打码中",
    "羽毛球": "羽毛球",
    "篮球": "篮球",
    "第一": "第一",
    "第二": "第二",
    "第三": "第三",
    "干杯": "干杯",
    "举手": "举手",
    "加一": "加一",
    "减一": "减一",
    "OK": "OK",
    "对": "对",
    "不": "不",
    "满分": "满分",
    "给力": "给力",
    "桃心": "桃心",
    "心碎": "心碎"
  };

  // TCC 表情 key 中文文本映射
  static final emojiZhNameMap = {
    "[TUIEmoji_Smile]": "[微笑]",
    "[TUIEmoji_Expect]": "[期待]",
    "[TUIEmoji_Blink]": "[眨眼]",
    "[TUIEmoji_Guffaw]": "[大笑]",
    "[TUIEmoji_KindSmile]": "[姨母笑]",
    "[TUIEmoji_Haha]": "[哈哈哈]",
    "[TUIEmoji_Cheerful]": "[愉快]",
    "[TUIEmoji_Speechless]": "[无语]",
    "[TUIEmoji_Amazed]": "[惊讶]",
    "[TUIEmoji_Sorrow]": "[悲伤]",
    "[TUIEmoji_Complacent]": "[得意]",
    "[TUIEmoji_Silly]": "[傻了]",
    "[TUIEmoji_Lustful]": "[色]",
    "[TUIEmoji_Giggle]": "[憨笑]",
    "[TUIEmoji_Kiss]": "[亲亲]",
    "[TUIEmoji_Wail]": "[大哭]",
    "[TUIEmoji_TearsLaugh]": "[哭笑]",
    "[TUIEmoji_Trapped]": "[困]",
    "[TUIEmoji_Mask]": "[口罩]",
    "[TUIEmoji_Fear]": "[恐惧]",
    "[TUIEmoji_BareTeeth]": "[龇牙]",
    "[TUIEmoji_FlareUp]": "[发怒]",
    "[TUIEmoji_Yawn]": "[打哈欠]",
    "[TUIEmoji_Tact]": "[机智]",
    "[TUIEmoji_Stareyes]": "[星星眼]",
    "[TUIEmoji_ShutUp]": "[闭嘴]",
    "[TUIEmoji_Sigh]": "[叹气]",
    "[TUIEmoji_Hehe]": "[呵呵]",
    "[TUIEmoji_Silent]": "[收声]",
    "[TUIEmoji_Surprised]": "[惊喜]",
    "[TUIEmoji_Askance]": "[白眼]",
    "[TUIEmoji_Ok]": "[OK]",
    "[TUIEmoji_Shit]": "[便便]",
    "[TUIEmoji_Monster]": "[怪兽]",
    "[TUIEmoji_Daemon]": "[恶魔]",
    "[TUIEmoji_Rage]": "[恶魔怒]",
    "[TUIEmoji_Fool]": "[衰]",
    "[TUIEmoji_Pig]": "[猪]",
    "[TUIEmoji_Cow]": "[牛]",
    "[TUIEmoji_Ai]": "[AI]",
    "[TUIEmoji_Skull]": "[骷髅]",
    "[TUIEmoji_Bombs]": "[炸弹]",
    "[TUIEmoji_Coffee]": "[咖啡]",
    "[TUIEmoji_Cake]": "[蛋糕]",
    "[TUIEmoji_Beer]": "[啤酒]",
    "[TUIEmoji_Flower]": "[花]",
    "[TUIEmoji_Watermelon]": "[瓜]",
    "[TUIEmoji_Rich]": "[壕]",
    "[TUIEmoji_Heart]": "[爱心]",
    "[TUIEmoji_Moon]": "[月亮]",
    "[TUIEmoji_Sun]": "[太阳]",
    "[TUIEmoji_Star]": "[星星]",
    "[TUIEmoji_RedPacket]": "[红包]",
    "[TUIEmoji_Celebrate]": "[庆祝]",
    "[TUIEmoji_Bless]": "[福]",
    "[TUIEmoji_Fortune]": "[发]",
    "[TUIEmoji_Convinced]": "[服]",
    "[TUIEmoji_Prohibit]": "[禁]",
    "[TUIEmoji_666]": "[666]",
    "[TUIEmoji_857]": "[857]",
    "[TUIEmoji_Knife]": "[刀]",
    "[TUIEmoji_Like]": "[赞]"
  };

  // TCC 表情旧 key 中文文本映射
  static final emojiZhOldNameMap = {
    "[Smile]": "[微笑]",
    "[Expect]": "[期待]",
    "[Blink]": "[眨眼]",
    "[Guffaw]": "[大笑]",
    "[KindSmile]": "[姨母笑]",
    "[Haha]": "[哈哈哈]",
    "[Cheerful]": "[愉快]",
    "[Speechless]": "[无语]",
    "[Amazed]": "[惊讶]",
    "[Sorrow]": "[悲伤]",
    "[Complacent]": "[得意]",
    "[Silly]": "[傻了]",
    "[Lustful]": "[色]",
    "[Giggle]": "[憨笑]",
    "[Kiss]": "[亲亲]",
    "[Wail]": "[大哭]",
    "[TearsLaugh]": "[哭笑]",
    "[Trapped]": "[困]",
    "[Mask]": "[口罩]",
    "[Fear]": "[恐惧]",
    "[BareTeeth]": "[龇牙]",
    "[FlareUp]": "[发怒]",
    "[Yawn]": "[打哈欠]",
    "[Tact]": "[机智]",
    "[Stareyes]": "[星星眼]",
    "[ShutUp]": "[闭嘴]",
    "[Sigh]": "[叹气]",
    "[Hehe]": "[呵呵]",
    "[Silent]": "[收声]",
    "[Surprised]": "[惊喜]",
    "[Askance]": "[白眼]",
    "[OK]": "[OK]",
    "[Shit]": "[便便]",
    "[Monster]": "[怪兽]",
    "[Daemon]": "[恶魔]",
    "[Rage]": "[恶魔怒]",
    "[Fool]": "[衰]",
    "[Pig]": "[猪]",
    "[Cow]": "[牛]",
    "[Ai]": "[AI]",
    "[Skull]": "[骷髅]",
    "[Bombs]": "[炸弹]",
    "[Coffee]": "[咖啡]",
    "[Cake]": "[蛋糕]",
    "[Beer]": "[啤酒]",
    "[Flower]": "[花]",
    "[Watermelon]": "[瓜]",
    "[Rich]": "[壕]",
    "[Heart]": "[爱心]",
    "[Moon]": "[月亮]",
    "[Sun]": "[太阳]",
    "[Star]": "[星星]",
    "[RedPacket]": "[红包]",
    "[Celebrate]": "[庆祝]",
    "[Bless]": "[福]",
    "[Fortune]": "[发]",
    "[Convinced]": "[服]",
    "[Prohibit]": "[禁]",
    "[666]": "[666]",
    "[857]": "[857]",
    "[Knife]": "[刀]",
    "[Like]": "[赞]"
  };

  static const List<int> defaultUnicodeEmojiList = [
    128513,
    128514,
    128515,
    128516,
    128517,
    128521,
    128522,
    128523,
    128524,
    128525,
    128527,
    128530,
    128531,
    128532,
    128534,
    128536,
    128538,
    128540,
    128542,
    128544,
    128545,
    128546,
    128547,
    128548,
    128549,
    128552,
    128553,
    128554,
    128555,
    128557,
    128560,
    128561,
    128562,
    128563,
    128565,
    128567,
    128568,
    128569,
    128570,
    128571,
    128572,
    128573,
    128574,
    128575,
    128576,
    128581,
    128582,
    128583,
    128584,
    128585,
    128586,
    128587,
    128588,
    128589,
    128590,
    128591,
    9989,
    9994,
    9995,
    10060,
    10062,
    10067,
    10068,
    10069,
    10071,
    10133,
    10134,
    10135,
    10160,
    128640,
    128643,
    128644,
    128645,
    128647,
    128649,
    128652,
    128655,
    128657,
    128658,
    128659,
    128661,
    128663,
    128665,
    128666,
    128674,
    128676,
    128677,
    128679,
    128680,
    128681,
    128682,
    128683,
    128684,
    128685,
    128690,
    128694,
    128697,
    128698,
    128699,
    128700,
    128701,
    128702,
    128704,
    127374,
    127377,
    127378,
    127379,
    127380,
    127381,
  ];
}
