import 'package:tim_ui_kit_sticker_plugin/utils/tim_custom_face_data.dart';

class TUIKitStickerConstData {
  static final List<CustomEmojiFaceData> emojiList = [
    CustomEmojiFaceData(
        name: '4349',
        icon: "面罩.png",
        isEmoji: true,
        list: [
          "面罩.png",
          "骷髅.png",
          "鲜花.png",
          "鼓掌.png",
        ]),
    CustomEmojiFaceData(name: 'tcc1', icon: "TUIEmoji_Smile.png", isEmoji: true, list: [
      "TUIEmoji_Like.png",
      "TUIEmoji_Ok.png",
      "TUIEmoji_Smile.png",
      "TUIEmoji_Expect.png",
      "TUIEmoji_Blink.png",
      "TUIEmoji_Guffaw.png",
      "TUIEmoji_KindSmile.png",
      "TUIEmoji_Haha.png",
      "TUIEmoji_Cheerful.png",
      "TUIEmoji_Speechless.png",
      "TUIEmoji_Amazed.png",
      "TUIEmoji_Sorrow.png",
      "TUIEmoji_Complacent.png",
      "TUIEmoji_Silly.png",
      "TUIEmoji_Lustful.png",
      "TUIEmoji_Giggle.png",
      "TUIEmoji_Kiss.png",
      "TUIEmoji_Wail.png",
      "TUIEmoji_TearsLaugh.png",
      "TUIEmoji_Trapped.png",
      "TUIEmoji_Mask.png",
      "TUIEmoji_Fear.png",
      "TUIEmoji_BareTeeth.png",
      "TUIEmoji_FlareUp.png",
      "TUIEmoji_Yawn.png",
      "TUIEmoji_Tact.png",
      "TUIEmoji_Stareyes.png",
      "TUIEmoji_ShutUp.png",
      "TUIEmoji_Sigh.png",
      "TUIEmoji_Hehe.png",
      "TUIEmoji_Silent.png",
      "TUIEmoji_Surprised.png",
      "TUIEmoji_Askance.png",
      "TUIEmoji_Shit.png",
      "TUIEmoji_Monster.png",
      "TUIEmoji_Daemon.png",
      "TUIEmoji_Rage.png",
      "TUIEmoji_Fool.png",
      "TUIEmoji_Pig.png",
      "TUIEmoji_Cow.png",
      "TUIEmoji_Ai.png",
      "TUIEmoji_Skull.png",
      "TUIEmoji_Bombs.png",
      "TUIEmoji_Coffee.png",
      "TUIEmoji_Cake.png",
      "TUIEmoji_Beer.png",
      "TUIEmoji_Flower.png",
      "TUIEmoji_Watermelon.png",
      "TUIEmoji_Rich.png",
      "TUIEmoji_Heart.png",
      "TUIEmoji_Moon.png",
      "TUIEmoji_Sun.png",
      "TUIEmoji_Star.png",
      "TUIEmoji_RedPacket.png",
      "TUIEmoji_Celebrate.png",
      "TUIEmoji_Bless.png",
      "TUIEmoji_Fortune.png",
      "TUIEmoji_Convinced.png",
      "TUIEmoji_Prohibit.png",
      "TUIEmoji_666.png",
      "TUIEmoji_857.png",
      "TUIEmoji_Knife.png",
    ])
  ];

  static final emoji4349ZhMapList = {
    '面罩': '面罩',
    '骷髅': "骷髅",
    '鲜花': "鲜花",
    '鼓掌': '鼓掌',
  };

  // TCC 表情 key 中文文本映射
  static final emojiZhNameMap = {
    "[TUIEmoji_Smile]": "[微笑]",
    "[TUIEmoji_Expect]": "[期待]",
    "[TUIEmoji_Blink]": "[眨眼]",
    "[TUIEmoji_Guffaw]": "[大笑]",
    "[TUIEmoji_KindSmile]": "[姨母笑]",
    "[TUIEmoji_Haha]": "[哈哈哈]",
    "[TUIEmoji_Cheerful]": "[愉快]",
    "[TUIEmoji_Speechless]": "[无语]",
    "[TUIEmoji_Amazed]": "[惊讶]",
    "[TUIEmoji_Sorrow]": "[悲伤]",
    "[TUIEmoji_Complacent]": "[得意]",
    "[TUIEmoji_Silly]": "[傻了]",
    "[TUIEmoji_Lustful]": "[色]",
    "[TUIEmoji_Giggle]": "[憨笑]",
    "[TUIEmoji_Kiss]": "[亲亲]",
    "[TUIEmoji_Wail]": "[大哭]",
    "[TUIEmoji_TearsLaugh]": "[哭笑]",
    "[TUIEmoji_Trapped]": "[困]",
    "[TUIEmoji_Mask]": "[口罩]",
    "[TUIEmoji_Fear]": "[恐惧]",
    "[TUIEmoji_BareTeeth]": "[龇牙]",
    "[TUIEmoji_FlareUp]": "[发怒]",
    "[TUIEmoji_Yawn]": "[打哈欠]",
    "[TUIEmoji_Tact]": "[机智]",
    "[TUIEmoji_Stareyes]": "[星星眼]",
    "[TUIEmoji_ShutUp]": "[闭嘴]",
    "[TUIEmoji_Sigh]": "[叹气]",
    "[TUIEmoji_Hehe]": "[呵呵]",
    "[TUIEmoji_Silent]": "[收声]",
    "[TUIEmoji_Surprised]": "[惊喜]",
    "[TUIEmoji_Askance]": "[白眼]",
    "[TUIEmoji_Ok]": "[OK]",
    "[TUIEmoji_Shit]": "[便便]",
    "[TUIEmoji_Monster]": "[怪兽]",
    "[TUIEmoji_Daemon]": "[恶魔]",
    "[TUIEmoji_Rage]": "[恶魔怒]",
    "[TUIEmoji_Fool]": "[衰]",
    "[TUIEmoji_Pig]": "[猪]",
    "[TUIEmoji_Cow]": "[牛]",
    "[TUIEmoji_Ai]": "[AI]",
    "[TUIEmoji_Skull]": "[骷髅]",
    "[TUIEmoji_Bombs]": "[炸弹]",
    "[TUIEmoji_Coffee]": "[咖啡]",
    "[TUIEmoji_Cake]": "[蛋糕]",
    "[TUIEmoji_Beer]": "[啤酒]",
    "[TUIEmoji_Flower]": "[花]",
    "[TUIEmoji_Watermelon]": "[瓜]",
    "[TUIEmoji_Rich]": "[壕]",
    "[TUIEmoji_Heart]": "[爱心]",
    "[TUIEmoji_Moon]": "[月亮]",
    "[TUIEmoji_Sun]": "[太阳]",
    "[TUIEmoji_Star]": "[星星]",
    "[TUIEmoji_RedPacket]": "[红包]",
    "[TUIEmoji_Celebrate]": "[庆祝]",
    "[TUIEmoji_Bless]": "[福]",
    "[TUIEmoji_Fortune]": "[发]",
    "[TUIEmoji_Convinced]": "[服]",
    "[TUIEmoji_Prohibit]": "[禁]",
    "[TUIEmoji_666]": "[666]",
    "[TUIEmoji_857]": "[857]",
    "[TUIEmoji_Knife]": "[刀]",
    "[TUIEmoji_Like]": "[赞]"
  };

  // TCC 表情旧 key 中文文本映射
  static final emojiZhOldNameMap = {
    "[Smile]": "[微笑]",
    "[Expect]": "[期待]",
    "[Blink]": "[眨眼]",
    "[Guffaw]": "[大笑]",
    "[KindSmile]": "[姨母笑]",
    "[Haha]": "[哈哈哈]",
    "[Cheerful]": "[愉快]",
    "[Speechless]": "[无语]",
    "[Amazed]": "[惊讶]",
    "[Sorrow]": "[悲伤]",
    "[Complacent]": "[得意]",
    "[Silly]": "[傻了]",
    "[Lustful]": "[色]",
    "[Giggle]": "[憨笑]",
    "[Kiss]": "[亲亲]",
    "[Wail]": "[大哭]",
    "[TearsLaugh]": "[哭笑]",
    "[Trapped]": "[困]",
    "[Mask]": "[口罩]",
    "[Fear]": "[恐惧]",
    "[BareTeeth]": "[龇牙]",
    "[FlareUp]": "[发怒]",
    "[Yawn]": "[打哈欠]",
    "[Tact]": "[机智]",
    "[Stareyes]": "[星星眼]",
    "[ShutUp]": "[闭嘴]",
    "[Sigh]": "[叹气]",
    "[Hehe]": "[呵呵]",
    "[Silent]": "[收声]",
    "[Surprised]": "[惊喜]",
    "[Askance]": "[白眼]",
    "[OK]": "[OK]",
    "[Shit]": "[便便]",
    "[Monster]": "[怪兽]",
    "[Daemon]": "[恶魔]",
    "[Rage]": "[恶魔怒]",
    "[Fool]": "[衰]",
    "[Pig]": "[猪]",
    "[Cow]": "[牛]",
    "[Ai]": "[AI]",
    "[Skull]": "[骷髅]",
    "[Bombs]": "[炸弹]",
    "[Coffee]": "[咖啡]",
    "[Cake]": "[蛋糕]",
    "[Beer]": "[啤酒]",
    "[Flower]": "[花]",
    "[Watermelon]": "[瓜]",
    "[Rich]": "[壕]",
    "[Heart]": "[爱心]",
    "[Moon]": "[月亮]",
    "[Sun]": "[太阳]",
    "[Star]": "[星星]",
    "[RedPacket]": "[红包]",
    "[Celebrate]": "[庆祝]",
    "[Bless]": "[福]",
    "[Fortune]": "[发]",
    "[Convinced]": "[服]",
    "[Prohibit]": "[禁]",
    "[666]": "[666]",
    "[857]": "[857]",
    "[Knife]": "[刀]",
    "[Like]": "[赞]"
  };

  static const List<int> defaultUnicodeEmojiList = [
    128513,
    128514,
    128515,
    128516,
    128517,
    128521,
    128522,
    128523,
    128524,
    128525,
    128527,
    128530,
    128531,
    128532,
    128534,
    128536,
    128538,
    128540,
    128542,
    128544,
    128545,
    128546,
    128547,
    128548,
    128549,
    128552,
    128553,
    128554,
    128555,
    128557,
    128560,
    128561,
    128562,
    128563,
    128565,
    128567,
    128568,
    128569,
    128570,
    128571,
    128572,
    128573,
    128574,
    128575,
    128576,
    128581,
    128582,
    128583,
    128584,
    128585,
    128586,
    128587,
    128588,
    128589,
    128590,
    128591,
    9989,
    9994,
    9995,
    10060,
    10062,
    10067,
    10068,
    10069,
    10071,
    10133,
    10134,
    10135,
    10160,
    128640,
    128643,
    128644,
    128645,
    128647,
    128649,
    128652,
    128655,
    128657,
    128658,
    128659,
    128661,
    128663,
    128665,
    128666,
    128674,
    128676,
    128677,
    128679,
    128680,
    128681,
    128682,
    128683,
    128684,
    128685,
    128690,
    128694,
    128697,
    128698,
    128699,
    128700,
    128701,
    128702,
    128704,
    127374,
    127377,
    127378,
    127379,
    127380,
    127381,
  ];
}
